### PR TITLE
make it middleware

### PR DESCRIPTION
**Pull request by kangguru**

### CODE REVIEW

**Comment by jhilden** [comment]
wow, that's really great stuff.  looking forward to merging this next week.

I'm thinking if it would make sense to release this under a new name in the railslove organisation, so that it gets a little more attention.  what do you think?

**Comment by kangguru** [comment]
:tada: happy to move this over, but why should we drop the name?

**Comment by jhilden** [comment]
The gem didn't get a lot of traction so far and I think it might partly also be due to the name.   That's why I was thinking about a rename as part of a move.

(The current user base is pretty small, so I don't think it would be a big problem.)

But I guess the question is, whether we can really think about a name that is sufficiently better.  Stuff that comes to mind:
* "i18n_frontend_key_inject"
* "i18n_keyhole" ;)

Hmm.  Don't really know.

**Comment by kangguru** [comment]
hm, not sure if the name correlates with "getting" traction ;) think of `kaminari` or any of the other weird named gems.

**Comment by kangguru** [comment]
:dancers:

**Pull request merged**
